### ISSUE TITLE
State-related interfaces should have the following structure I[Component]State

### ISSUE THREAD

**Issue by Rodmg** [ksquarelabsmx/react-guidelines#1]
Title: State-related interfaces should have the following structure I[Component]State
Date: 26/02/2019
By: Rodrigo Mendez

## Motivations
I see that you already have a similar rule for Prop-related interfaces, why not add one for State-related ones?

I know that we are favoring Functional Components over Class-based, but anyway we may need to use Class-based, and in that case we should also pass a State interface.

## Sources
Personal experience

**Comment by mishelashala** [comment]
Yeah sure, we can add it. Do you want to create a PR or do I label the issue with `help-wanted` so someone else can pick it up?
