### ISSUE TITLE
Prefer destructuring for access to functions props and properties in objects

### ISSUE THREAD

**Issue by basultobdKs** [ksquarelabsmx/react-guidelines#5]
Title: Prefer destructuring for access to functions props and properties in objects
Date:  27/02/2019
By: Daniel Basulto

## Motivations
1. Better understanding of functions interfaces.
2. Explicit better than implicit.
3. Avoid the use of the `.` for access to object properties.
4. In general contribute to code readability and maintainability. 

## Examples
```js

// For props with "one nested level"

const user = {
 name: "John Doe",
 age: 50
};

// Good
const useUserInfo = (user) => {
  const { name, age } = user;
  //...
} 

// Better
const useUserInfo = ({ name, age }) => {
  //...
} 

useUserInfo(user);

// For props with "many nested levels"

const user = {
 name: {
    first: "John",
    last: "Doe"
 },
 age: 50
};

// Good
const useUserInfo = (user) => {
  const { name: { first, last }, age } = user;
  //...
} 

// This is the best for small objects
const useUserInfo = ({ name: { first, last }, age }) => {
  //...
} 

// This is the best for any size I think
const useUserInfo = ({ name, age }) => {
  const { first, last } = name;
  //...
} 

useUserInfo(user);

// For arrays

const carsList = [
  {
    brand: 'ferrari',
    type: 'sportscar',
    engine: {
        horsepower: 600,
        liters: 4,
        fuel: 'gas'
     },
     wheels: 4
  },
  {
    brand: 'porshe',
    type: 'sportscar',
    engine: {
        horsepower: 455,
        liters: 6,
        fuel: 'gas'
     },
     wheels: 4
  },
];

const [ferrari, porsche] = carsList;


```
## Sources
[ExploringJS. Destructuring](http://exploringjs.com/es6/ch_destructuring.html)
[ES6 Destructuring: The Complete Guide](https://codeburst.io/es6-destructuring-the-complete-guide-7f842d08b98f)
[Destructuring MDN](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Operadores/Destructuring_assignment)

**Comment by mishelashala** [comment]
LGTM, could you add an example handling name prop collision?

**Comment by basultobdKs** [comment]
@mishelashala do you refer a situation like this:

```js
const func = ({ prop1 } , { prop1 }) => {
  //...
}
```

**Comment by mishelashala** [comment]
yeah @basultobdKs, something like that

**Comment by basultobdKs** [comment]
@mishelashala In that case I suggest to rename the prop more related with the context, I know that can be tricky, so maybe just provide a more descriptive name.

```js
const func = ({ name: UserName } , { name: companyName }) => {
  //...
}


const user = {
  name: "John Doe",
  //...
};

const company = {
  name: "Airbnb",
  //...
};

func(user, company)
```

**Comment by mishelashala** [comment]
ok, if everyone is ok with it then create a PR :)
